package com.renovabio.renovabioapi.model;

public enum StatusTroca {
    GERADO,
    RESGATADO,  //SÓ USO ESSE, MAS SE EM UM FUTURO O PARCEIRO VALIDAR O VOUCHER, A GENTE PODE MUDAR PARA GERADO E DEPOIS PARA RESGATADO E SE QUISER CANCELAR, CANCELADO
    CANCELADO
}